# Generated by Django 5.0.6 on 2024-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
